version: "3.8"
services:

  costore:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    restart: always
    ports:
      - "8200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 5s
      timeout: 5s
      retries: 5

  aipm:
    image: aipm/web-test
    restart: always
    ports:
      - "8201:8081"
    command: python3 /home/aipm-web/manage.py runserver 0.0.0.0:8081

  pandadb:
    depends_on:
      - costore
      - aipm
    image: pandadb:0.2
    ports:
      - "8074:7410"
      - "8075:7510"
      - "8076:7610"
    restart: always