version: '3'

services:
  costore:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    restart: always
    ports:
      - "8100:9100"
      - "8200:9200"
      - "8300:9300"

  pandadb:
    depends_on:
      - costore
    build: .
    ports:
      - "7010:7410"
    restart: always